server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:file:~/SpringMVC_API
    driver-class-name: org.h2.Driver
    username: spring-boot
    password: paulpw
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
