#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: ubuntu
#    password: 88888888

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
